source 'https://gitlab.com/TahaElsheikh1/specs.git'
source 'https://github.com/CocoaPods/Specs'

use_frameworks!

target 'VFExtensions_Example' do
    pod 'VFExtensions', :path => '../'

  target 'VFExtensions_Tests' do
    inherit! :search_paths

  end
end
